# Generated by Django 2.2 on 2022-12-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_students_major_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='major_id',
        ),
    ]
